---
# defaults file for LUA 

# passwd: 'admin' 
# linux_user: serveradmin
# ansible_user: ansadm
# ansible_password: 
# ansible_become_user: root
# ansible_become_method: sudo 
# ansible_become_pass:  

ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 
ansible_user: ansadm
ansible_password: "{{vault_ansible_password}}"   
ansible_sudo_pass: "{{vault_ansible_password}}" 

teleport_sever_ip: "172.19.45.245"
teleport_version: "7.3.3"
teleport_url: "https://get.gravitational.com/teleport_{{ teleport_version }}_amd64.deb" 
 
teleport_pidfile: '/run/teleport.pid'
teleport_config_path: "/etc/teleport.yaml"
teleport_nodename: 'teleport'
teleport_auth_token: ''
teleport_auth_servers:
  - 172.19.45.245:3025
teleport_data_dir: '/var/lib/teleport'

teleport_log_level: 'INFO' 
teleport_log_output: 'text'
teleport_storage_type: 'bolt'


teleport_default_address: '0.0.0.0'
teleport_ca_pin: 'sha256:47bc67b65b3b5caaa5482a51478fdcc546060921c5aed57ec816b8db4767c273' 

# auth service
teleport_auth_enabled: false
teleport_auth_listen_address: '{{ teleport_default_address | ipwrap }}:3025'
teleport_auth_cluster_name: 'main'
teleport_auth_tokens_node: []
teleport_auth_tokens_proxy: []
teleport_auth_tokens_auth: []
teleport_auth_trusted_clusters: []
teleport_auth_oidc_connectors: []

# ssh service
teleport_ssh_enabled: true
teleport_ssh_listen_address: '{{ teleport_default_address | ipaddr }}:3022'
teleport_commands: [] 
teleport_pam_enabled: true

# proxy service
teleport_proxy_enabled: false
teleport_proxy_listen_address: '{{ teleport_default_address | ipaddr }}:3023'
teleport_proxy_web_listen_address: '{{ teleport_default_address | ipaddr }}:3080'
teleport_proxy_tunnel_listen_address: '{{ teleport_default_address | ipaddr }}:3024'
teleport_proxy_https_key_file: ''
teleport_proxy_https_cert_file: '' 

# Labels service 
teleport_env_node: 'prod'
teleport_role_node: 'node'
teleport_type_node: 'gitlab-ee'